# Generated by Django 4.1 on 2022-08-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'The email must be unique.'}, max_length=150, unique=True),
        ),
    ]
